name: 'Multi-job Slack notifications'
description: 'Single slack message notifications for Github workflows with more than one job. Updates as your jobs run.'
inputs:
  slack_bot_token:
    description: 'Slack token used to post to your channel.'
    required: true
  slack_channel:
    description: 'ID or string for the target Slack channel.'
    required: true
  job:
    description: 'Current Job JSON'
    required: true
outputs:
  updated_at:
    description: 'The timestamp for when the slack message was last updated.'
runs:
  using: 'node12'
  main: 'dist/index.js init'
  post: 'dist/index.js update'
  post-if: always()
