name: Ensure action is runnable
push:
  branches:
    - master

jobs:
  runnable:
    runs-on: ubuntu-latest
    steps:
    - uses: voxmedia/gh-action-multi-job-slack@master
    - uses: ./
      with:
        milliseconds: 1000
