name: Tests
on: [push, pull_request]

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # # test action works running from the graph
  # TODO: enable this once we have a 1.0 release
  # github_graph:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: voxmedia/gh-action-multi-job-slack@v1.0.0
  #   - uses: ./
  #     with:
  #       milliseconds: 1000
